version: '3'

services:
  nginx:
      image: nginx
      build:
        context: nginx
      ports:
        - 8080:80
      restart: always
      tty: true
      # volumes:
      #   - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app
      networks:
        - node-network

  app:
    container_name: app
    build: 
      context: node 
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=nodedb
    depends_on:
      - db
    command: node index.js

  
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge